In [2]:
#Preprocessing data to get the most popular movies for a test user
# import libraries 

import pandas as pd
import numpy as np
import time

In [13]:
movies = pd.read_csv('datasets/movies_metadata.csv')

C:\Users\FATIMA\AppData\Local\Temp\ipykernel_5976\3612041176.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv('datasets/movies_metadata.csv')

In [14]:
movies.shape

(45466, 24)

In [15]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [16]:
# recommendation will be based on these features only
movies = movies.loc[:,['id','imdb_id','title','poster_path','vote_average','vote_count','release_date']]

In [9]:
movies_sorted = movies.sort_values(by = 'vote_count',ascending=False)

In [10]:
movies_sorted

,id,imdb_id,title,poster_path,vote_average,vote_count
0,862,tt0114709,Toy Story,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,7.7,5415.0
1,8844,tt0113497,Jumanji,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,6.9,2413.0
5,949,tt0113277,Heat,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,7.7,1886.0
9,710,tt0113189,GoldenEye,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,6.6,1194.0
8,9091,tt0114576,Sudden Death,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,5.5,174.0
4,11862,tt0113041,Father of the Bride Part II,/e64sOI48hQXyru7naBFyssKFxVd.jpg,5.7,173.0
6,11860,tt0114319,Sabrina,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,6.2,141.0
2,15602,tt0113228,Grumpier Old Men,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,6.5,92.0
7,45325,tt0112302,Tom and Huck,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,5.4,45.0
3,31357,tt0114885,Waiting to Exhale,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,6.1,34.0

In [11]:
movies_sorted.to_csv('popularity.csv')

In [17]:
movies

,id,imdb_id,title,poster_path,vote_average,vote_count,release_date
0,862,tt0114709,Toy Story,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,7.7,5415.0,1995-10-30
1,8844,tt0113497,Jumanji,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,6.9,2413.0,1995-12-15
2,15602,tt0113228,Grumpier Old Men,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,6.5,92.0,1995-12-22
3,31357,tt0114885,Waiting to Exhale,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,6.1,34.0,1995-12-22
4,11862,tt0113041,Father of the Bride Part II,/e64sOI48hQXyru7naBFyssKFxVd.jpg,5.7,173.0,1995-02-10
...,...,...,...,...,...,...,...
45461,439050,tt6209470,Subdue,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,4.0,1.0,NaN
45462,111109,tt2028550,Century of Birthing,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,9.0,3.0,2011-11-17
45463,67758,tt0303758,Betrayal,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,3.8,6.0,2003-08-01
45464,227506,tt0008536,Satan Triumphant,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,0.0,0.0,1917-10-21
45465,461257,tt6980792,Queerama,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,0.0,0.0,2017-06-09

In [18]:
print(type(movies.release_date[0]))

<class 'str'>

In [37]:
latest = movies.sort_values('release_date',ascending = False)

In [38]:
latest_df = latest[0:10]

In [39]:
latest_df

,id,imdb_id,title,poster_path,vote_average,vote_count,release_date
35587,2014-01-01,0,NaN,Avalanche Sharks,NaN,NaN,22
26559,76600,tt1630029,Avatar 2,/wvpOVl37PR21mENpmZKVwrLUsRD.jpg,0.0,58.0,2020-12-16
38885,299782,tt0069049,The Other Side of the Wind,/wtSpgCw6MmSxGYysaa17f0a9U4y.jpg,0.0,1.0,2018-12-31
30402,38700,tt1502397,Bad Boys for Life,/2GwwyfykFAf3jKXFWMkBiLgTi3k.jpg,0.0,12.0,2018-11-07
38130,332283,tt3906082,Mary Shelley,/AnHutc9eDDrVXvlmYFohEougTHq.jpg,0.0,1.0,2018-04-25
44535,412059,tt5613402,Mobile Homes,/of72rtl3j0C9yJMlSJZHXnaByz8.jpg,0.0,1.0,2018-04-04
33359,302349,tt3038708,Iron Sky: The Coming Race,/dJTn8jUruV3llF1sGxSakd3hC63.jpg,0.0,0.0,2018-03-01
33358,252983,tt3498786,Sly Cooper,/rw36cctUD5kPCNCxFYsQ7F205B8.jpg,0.0,0.0,2017-12-31
30536,245842,tt2328678,The King's Daughter,/xBLskcmADJYJrDw3O04XdMvrE2m.jpg,0.0,4.0,2017-12-30
44301,341689,tt3859310,How to Talk to Girls at Parties,/tyCt5dQ2yhfEtWcP3KqMgtFk7s0.jpg,0.0,10.0,2017-12-27